[[frn.fields]]
from = "frn:laenge"
to = "media.duration"

[[frn.fields]]
from = "frn:licence"
to = "licence"

[[frn.fields]]
from = "dc:creator"
to = "creator"

[[frn.fields]]
from = "frn:title"
to = "headline"

[[frn.fields]]
from = "frn:art"
to = "genre"

[[frn.fields]]
from = "frn:radio"
to = "publisher"

[[frn.fields]]
from = "frn:last_update"
to = "dateModified"

[[frn.fields]]
from = "pubDate"
to = "datePublished"

[[cba.fields]]
from = "cba:duration"
to = "media.duration"

[[cba.fields]]
from = "cba:teaser"
to = "abstract"

[[cba.fields]]
from = "cba:teaser"
to = "abstract"

[[cba.fields]]
from = "cba:productiondate"
to = "dateProduction"
